version: "3"
services:
  psql:
    # replace username/repo:tag with your name and image details
    image: postgres:9.6
    env_file:
      - .env
    volumes:
      - "$HOME:/home"
    networks:
      - postgresServerNetwork

networks:
  postgresServerNetwork:
    # make sure the external network development is created in advance by start the postgres server docker-compose first
    name: development
    external: true
